# Generated by Django 2.2.7 on 2019-11-28 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Details Prêt',
            },
        ),
        migrations.CreateModel(
            name='Virement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=250, verbose_name='Numéro Virement')),
                ('montantvire', models.FloatField(verbose_name='Montant Virement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Virements',
            },
        ),
        migrations.CreateModel(
            name='TypeSouscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Types de Souscription',
            },
        ),
        migrations.CreateModel(
            name='TypePret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Types de Prêt',
            },
        ),
        migrations.CreateModel(
            name='TypeCompteTiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Types de Compte de Tiers',
            },
        ),
        migrations.CreateModel(
            name='TypeCompte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Types de Compte',
            },
        ),
        migrations.CreateModel(
            name='TypeClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Types Clients',
            },
        ),
        migrations.CreateModel(
            name='TypeBanque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Types de Banque',
            },
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Traitements',
            },
        ),
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='media/users', verbose_name='Photo de profil')),
                ('noms', models.CharField(max_length=250, verbose_name='Noms')),
                ('prenoms', models.CharField(max_length=250, verbose_name='Prénoms')),
                ('datenaissance', models.DateField(verbose_name='Date de Naissance')),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=250, unique=True, verbose_name='Téléphone')),
                ('profession', models.CharField(max_length=250, verbose_name='Profession')),
                ('adresse', models.CharField(max_length=250, verbose_name='Adresse')),
                ('ville', models.CharField(max_length=250, verbose_name='Ville')),
                ('nationalite', models.CharField(max_length=250, verbose_name='Nationalité')),
                ('quartier', models.CharField(max_length=250, verbose_name='Quartier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Tierses Personnes',
            },
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Statuts',
            },
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Souscriptions',
            },
        ),
        migrations.CreateModel(
            name='Simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Simples Retraits',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Secteurs',
            },
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=250, verbose_name='Motif')),
                ('montantretire', models.FloatField(verbose_name='Montant Retiré')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Retraits',
            },
        ),
        migrations.CreateModel(
            name='RemiseCheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250, verbose_name='Libellé')),
                ('valeur', models.FloatField(verbose_name='Remise sur Chèque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Remises sur Chèque',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField(max_length=250, verbose_name='Libellé')),
                ('valeur', models.FloatField(verbose_name='Montant Prêté')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('detailpret', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to='gestion.DetailPret', verbose_name='Details Prêt')),
                ('typepret', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to='gestion.TypePret', verbose_name='Type de Prêt')),
            ],
            options={
                'verbose_name_plural': 'Les Prêts',
            },
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Prestations',
            },
        ),
        migrations.CreateModel(
            name='Ouverture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Ouvertures',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Operations',
            },
        ),
        migrations.CreateModel(
            name='Mandataire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='media/users', verbose_name='Photo de profil')),
                ('noms', models.CharField(max_length=250, verbose_name='Noms')),
                ('prenoms', models.CharField(max_length=250, verbose_name='Prénoms')),
                ('datenaissance', models.DateField(verbose_name='Date de Naissance')),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=250, unique=True, verbose_name='Téléphone')),
                ('profession', models.CharField(max_length=250, verbose_name='Profession')),
                ('adresse', models.CharField(max_length=250, verbose_name='Adresse')),
                ('ville', models.CharField(max_length=250, verbose_name='Ville')),
                ('nationalite', models.CharField(max_length=250, verbose_name='Nationalité')),
                ('quartier', models.CharField(max_length=250, verbose_name='Quartier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Personnes Mandataires',
            },
        ),
        migrations.CreateModel(
            name='Mad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'MAD',
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Livraisons',
            },
        ),
        migrations.CreateModel(
            name='Frais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('montantfrais', models.FloatField(verbose_name='Montant des Frais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Montants des Frais',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='media/agence', verbose_name='Logo')),
                ('sigle', models.CharField(max_length=250, verbose_name='Sigle')),
                ('libelle', models.CharField(max_length=250, verbose_name='Libellé')),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='Email')),
                ('phone1', models.CharField(max_length=250, unique=True, verbose_name='Téléphone')),
                ('phone2', models.CharField(max_length=250, unique=True, verbose_name='Téléphone 2')),
                ('fax', models.CharField(max_length=250, verbose_name='Fax')),
                ('adresse', models.CharField(max_length=250, verbose_name='Adresse')),
                ('ville', models.CharField(max_length=250, verbose_name='Ville')),
                ('quartier', models.CharField(max_length=250, verbose_name='Quartier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': "Fonctions d'une Agence",
            },
        ),
        migrations.CreateModel(
            name='Fermeture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Fermetures',
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Engagements',
            },
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.TextField(verbose_name='Description')),
                ('valeurcfa', models.FloatField(verbose_name='Valeur en Frs CFA')),
                ('valeurus', models.FloatField(verbose_name='Valeur en Dollars US')),
                ('valeureuro', models.FloatField(verbose_name='Valeur en Euros')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Devises',
            },
        ),
        migrations.CreateModel(
            name='Deroge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Retraits Dérogés',
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=250, verbose_name='Motif')),
                ('montantverse', models.FloatField(verbose_name='Montant Versé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Dépôts',
            },
        ),
        migrations.CreateModel(
            name='CompteTiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=250, verbose_name='Numéro du Compte')),
                ('solde', models.FloatField(verbose_name='Solde')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('typecompte', models.ForeignKey(blank=True, null=True, on_delete='cascade', to='gestion.TypeCompte')),
            ],
            options={
                'verbose_name_plural': 'Les Comptes Tiers',
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=250, verbose_name='Numéro Général')),
                ('ouverture', models.DateField(max_length=250, verbose_name='Ouverture')),
                ('cloture', models.DateField(max_length=250, verbose_name='Clôture')),
                ('intitule', models.CharField(blank=True, max_length=250, null=True, verbose_name='Intitulé')),
                ('statut', models.CharField(choices=[('En Activité', 'En Activité'), ('En Arrêt', 'En Arrêt')], default='En Activité', max_length=130, verbose_name='Statut du Compte')),
                ('matricule', models.CharField(max_length=250, verbose_name='Matricule Fonctionnaire')),
                ('montancartone', models.FloatField(verbose_name='Montant Cartoné')),
                ('numcpte', models.CharField(max_length=250, verbose_name='Compte Intérêts')),
                ('decouvertauto', models.FloatField(verbose_name='Découvert Autorisé')),
                ('debut', models.DateField(max_length=250, verbose_name='Début')),
                ('fin', models.DateField(max_length=250, verbose_name='Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('typecompte', models.ForeignKey(blank=True, null=True, on_delete='cascade', to='gestion.TypeCompte', verbose_name='Nature du Compte')),
            ],
            options={
                'verbose_name_plural': 'Les Comptes',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='media/users', verbose_name='Photo de profil')),
                ('noms', models.CharField(max_length=250, verbose_name='Noms')),
                ('prenoms', models.CharField(max_length=250, verbose_name='Prénoms')),
                ('datenaissance', models.DateField(verbose_name='Date de Naissance')),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=250, unique=True, verbose_name='Téléphone')),
                ('profession', models.CharField(max_length=250, verbose_name='Profession')),
                ('adresse', models.CharField(max_length=250, verbose_name='Adresse')),
                ('ville', models.CharField(max_length=250, verbose_name='Ville')),
                ('nationalite', models.CharField(max_length=250, verbose_name='Nationalité')),
                ('quartier', models.CharField(max_length=250, verbose_name='Quartier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('typeclient', models.ForeignKey(blank=True, null=True, on_delete='cascade', to='gestion.TypeClient')),
            ],
            options={
                'verbose_name_plural': 'Les Clients',
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=250, verbose_name='Numéro Compte')),
                ('montant', models.FloatField(verbose_name='Montant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Chèques',
            },
        ),
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=250, verbose_name='Numéro Carte')),
                ('solde', models.FloatField(verbose_name='Solde')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Cartes',
            },
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=250, verbose_name='Numéro de Caisse')),
                ('solde', models.FloatField(verbose_name='Solde')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Caisses',
            },
        ),
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='media/banque', verbose_name='Logo')),
                ('sigle', models.CharField(max_length=250, verbose_name='Sigle')),
                ('libelle', models.CharField(max_length=250, verbose_name='Libellé')),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='Email')),
                ('phone1', models.CharField(max_length=250, unique=True, verbose_name='Téléphone')),
                ('phone2', models.CharField(max_length=250, unique=True, verbose_name='Téléphone 2')),
                ('fax', models.CharField(max_length=250, verbose_name='Fax')),
                ('adresse', models.CharField(max_length=250, verbose_name='Adresse')),
                ('ville', models.CharField(max_length=250, verbose_name='Ville')),
                ('quartier', models.CharField(max_length=250, verbose_name='Quartier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Banques',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='media/users', verbose_name='Photo de profil')),
                ('noms', models.CharField(max_length=250, verbose_name='Noms')),
                ('prenoms', models.CharField(max_length=250, verbose_name='Prénoms')),
                ('datenaissance', models.DateField(verbose_name='Date de Naissance')),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=250, unique=True, verbose_name='Téléphone')),
                ('profession', models.CharField(max_length=250, verbose_name='Profession')),
                ('adresse', models.CharField(max_length=250, verbose_name='Adresse')),
                ('ville', models.CharField(max_length=250, verbose_name='Ville')),
                ('nationalite', models.CharField(max_length=250, verbose_name='Nationalité')),
                ('quartier', models.CharField(max_length=250, verbose_name='Quartier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('typeclient', models.ForeignKey(blank=True, null=True, on_delete='cascade', to='gestion.TypeClient')),
            ],
            options={
                'verbose_name_plural': 'Les Agents',
            },
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='media/agence', verbose_name='Logo')),
                ('sigle', models.CharField(max_length=250, verbose_name='Sigle')),
                ('libelle', models.CharField(max_length=250, verbose_name='Libellé')),
                ('email', models.EmailField(max_length=250, unique=True, verbose_name='Email')),
                ('phone1', models.CharField(max_length=250, unique=True, verbose_name='Téléphone')),
                ('phone2', models.CharField(max_length=250, unique=True, verbose_name='Téléphone 2')),
                ('fax', models.CharField(max_length=250, verbose_name='Fax')),
                ('adresse', models.CharField(max_length=250, verbose_name='Adresse')),
                ('ville', models.CharField(max_length=250, verbose_name='Ville')),
                ('quartier', models.CharField(max_length=250, verbose_name='Quartier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Agences',
            },
        ),
    ]
