# Generated by Django 2.2.7 on 2019-11-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='cloture',
            field=models.DateField(verbose_name='Clôture'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='debut',
            field=models.DateField(verbose_name='Début'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='ouverture',
            field=models.DateField(verbose_name='Ouverture'),
        ),
    ]
